
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: focusflow
      POSTGRES_USER: focusflow_user
      POSTGRES_PASSWORD: focusflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focusflow_user -d focusflow"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
